### ISSUE TITLE
Misdesigned checkout experience when logged in with Coinbase

### ISSUE THREAD

**Issue by georgschlenkhoff** [coinbase/coinbase-spree#2]
I have integrated Spree plugin. Thank you guys for supporting Spree.

When I'm logged in with Coinbase the design looks clunky.

![coinbase_spree_checkout](https://cloud.githubusercontent.com/assets/2112017/3276277/287c5752-f347-11e3-9121-9a7a4eaceea6.png)

The button would look better placed in the right corner.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
