### ISSUE TITLE
Missing Versions Specific Branches

### ISSUE THREAD

**Issue by jameshilliard** [coinbase/coinbase-spree#4]
There do not appear to be version specific branches for anything other than spree 2-1-stable, would it be possible to have version specific branches for 2-2-stable and 2-3-stable and a master branch that matches with spree's current master branch?

**Comment by interhive** [comment]
Any chance at getting a 2.4.x-compatible version? Thanks!

**Comment by interhive** [comment]
Compatible with Spree 3.0?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
